@echo off
set "PATH=C:\nodejs\node-v20.19.0-win-x64;%PATH%"
echo Starting ClinicPlus...

echo 1. Starting Backend Server...
start cmd /k "cd backend && npm run dev"

echo 2. Starting Frontend (Vite)...
start cmd /k "cd frontend && npm run dev"

echo Done! Both servers are starting...
